### ISSUE TITLE
Install method issues

### ISSUE THREAD

**Issue by allthesignals** [ericyoungberg/prql#35]
## install.sh
  - `sudo ./install.sh` throws `cp: build/prql: No such file or directory`.

## Go
 - `go get github.com/prql/prql` throws `package github.com/prql/prql: no Go files in /Users/mgardner/go/src/github.com/prql/prql`

Need to:

1. `brew install dep`
2. Install `staticcheck`: https://github.com/dominikh/go-tools#installation
3. Manually copy the contents of the generated `build` folder into `usr/local/bin`.

When first adding a server, the following error is triggered, maybe because prqld isn't added:
```
$ sudo prql databases new \
 --name factfinderv2 \
 --driver postgres \
 --port 5432
Added database factfinderv2
FATA[0000] Could not refresh databases pool in prqld
```

The documented `curl` command does not appear to hit the server... maybe it's configured wrong (just throws 400)... I got around this by just using Postman.

When creating tokens, what is `hostname`? Confused why I need to specify the hostname for a token. In any case, it doesn't seem to get recorded when I try a combination of `0.0.0.0` or `localhost`:

Querying throws me this error:
```bash
curl -X GET \
  'http://127.0.0.1:1999/?query=SELECT%20*%20FROM%20housing%20LIMIT%205' \
  -H 'prql-token: 85c5ee110e875a7625478551aabf14ab'
```

```terminal
PANI[0362] Invalid database server name
2019/01/14 15:37:08 http: panic serving 127.0.0.1:50574: &{0xc000094460 map[] 2019-01-14 15:37:08.149235 -0500 EST m=+362.078526370 panic Invalid database server name <nil>}
goroutine 39 [running]:
net/http.(*conn).serve.func1(0xc00017e140)
	/usr/local/Cellar/go/1.11.4/libexec/src/net/http/server.go:1746 +0xd0
panic(0x135d660, 0xc000154370)
	/usr/local/Cellar/go/1.11.4/libexec/src/runtime/panic.go:513 +0x1b9
github.com/prql/prql/vendor/github.com/sirupsen/logrus.Entry.log(0xc000094460, 0xc000148330, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/Users/mgardner/go/src/github.com/prql/prql/vendor/github.com/sirupsen/logrus/entry.go:126 +0x2a7
github.com/prql/prql/vendor/github.com/sirupsen/logrus.(*Entry).Panic(0xc0001540f0, 0xc000152250, 0x1, 0x1)
	/Users/mgardner/go/src/github.com/prql/prql/vendor/github.com/sirupsen/logrus/entry.go:194 +0xb2
github.com/prql/prql/vendor/github.com/sirupsen/logrus.(*Logger).Panic(0xc000094460, 0xc000152250, 0x1, 0x1)
	/Users/mgardner/go/src/github.com/prql/prql/vendor/github.com/sirupsen/logrus/logger.go:244 +0x6d
main.(*Logger).Panic(0xc0000fa0e0, 0xc000152250, 0x1, 0x1)
	/Users/mgardner/go/src/github.com/prql/prql/prqld/log.go:55 +0xa4
main.getDatabase(0xc00014a1e0, 0x20, 0x12ba324)
	/Users/mgardner/go/src/github.com/prql/prql/prqld/databases.go:63 +0x43c
main.performQuery(0xc00014a280, 0x1d, 0xc00014a1e0, 0x20, 0x0, 0x0, 0x0)
	/Users/mgardner/go/src/github.com/prql/prql/prqld/databases.go:34 +0x50
main.handler(0x13c68a0, 0xc0001941c0, 0xc00018c500)
	/Users/mgardner/go/src/github.com/prql/prql/prqld/server.go:91 +0x637
net/http.HandlerFunc.ServeHTTP(0x1382d70, 0x13c68a0, 0xc0001941c0, 0xc00018c500)
	/usr/local/Cellar/go/1.11.4/libexec/src/net/http/server.go:1964 +0x44
net/http.(*ServeMux).ServeHTTP(0xc00007f170, 0x13c68a0, 0xc0001941c0, 0xc00018c500)
	/usr/local/Cellar/go/1.11.4/libexec/src/net/http/server.go:2361 +0x127
net/http.serverHandler.ServeHTTP(0xc000081040, 0x13c68a0, 0xc0001941c0, 0xc00018c500)
	/usr/local/Cellar/go/1.11.4/libexec/src/net/http/server.go:2741 +0xab
net/http.(*conn).serve(0xc00017e140, 0x13c6b60, 0xc000176400)
	/usr/local/Cellar/go/1.11.4/libexec/src/net/http/server.go:1847 +0x646
created by net/http.(*Server).Serve
	/usr/local/Cellar/go/1.11.4/libexec/src/net/http/server.go:2851 +0x2f5
```

**Comment by ericyoungberg** [comment]
My docs are the fucking worst.

**Comment by allthesignals** [comment]
@ericyoungberg they're fine! I'm your first user!!!

**Comment by ericyoungberg** [comment]
Thanks for your patience and collaboration haha

**Comment by ericyoungberg** [comment]
I'm closing this after integrating some of this feedback into the implementation itself as well as in the README. Some of these issues, such as the programs not being copied in the right order, will be alleviated in beta. The beta will have better deployment methods.

**Comment by allthesignals** [comment]
@ericyoungberg SWEET!!!
